name: GitHub Actions Demo
on:
  push:
    branches:
      - main
jobs:
  init:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ "17"]
    steps:
      - uses: actions/checkout@v4
      - name: Starting Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
    - name: install modules
      run: npm install -f
    - name: build project
      run: npm run build
    - name: unit test
      run: npm run test
    - name: e2e test
      run: npm run test:e2e
    - name: lint code
      run: npm run lint


